--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.cliente (
    contrasena character varying(255) NOT NULL,
    estado boolean NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.cliente OWNER TO "user";

--
-- Name: cuenta; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.cuenta (
    numero_cuenta character varying(255) NOT NULL,
    estado boolean NOT NULL,
    saldo_inicial double precision NOT NULL,
    tipo_cuenta character varying(255) NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.cuenta OWNER TO "user";

--
-- Name: movimiento; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.movimiento (
    movimiento_id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    saldo double precision NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor double precision NOT NULL,
    numero_cuenta character varying(255) NOT NULL
);


ALTER TABLE public.movimiento OWNER TO "user";

--
-- Name: movimiento_movimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.movimiento ALTER COLUMN movimiento_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    direccion character varying(255) NOT NULL,
    edad integer NOT NULL,
    genero character varying(255) NOT NULL,
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL
);


ALTER TABLE public.persona OWNER TO "user";

--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id);


--
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (numero_cuenta);


--
-- Name: movimiento movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT movimiento_pkey PRIMARY KEY (movimiento_id);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: persona ukr5vsms84ih2viwd6tatk9o5pq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion);


--
-- Name: cliente fk33cy8185r4ecu0qd6tyra3drb; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fk33cy8185r4ecu0qd6tyra3drb FOREIGN KEY (cliente_id) REFERENCES public.persona(id);


--
-- Name: cuenta fk4p224uogyy5hmxvn8fwa2jlug; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT fk4p224uogyy5hmxvn8fwa2jlug FOREIGN KEY (cliente_id) REFERENCES public.cliente(cliente_id);


--
-- Name: movimiento fkk10u787s9re28fue9gdscb5kt; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT fkk10u787s9re28fue9gdscb5kt FOREIGN KEY (numero_cuenta) REFERENCES public.cuenta(numero_cuenta);


--
-- PostgreSQL database dump complete
--

